### ISSUE TITLE
Don't check that user exists before authenticating

### ISSUE THREAD

**Issue by sshisk** [14mRh4X0r/matrix-synapse-pam#2]
In my case we use pam_pgsql module for authenticating against `users` table in PostgreSQL, which is also used by other services like mail. Thus NSS doesn't (and shouldn't) have entries on these users, they are virtual users which only exist in a particular PAM service. Therefore auth doesn't work for me unless I remove `getpwnam` call. Maybe we can remove it altogether or add a configuration option? Or maybe I'm overlooking some other solution?

**Comment by 14mRh4X0r** [comment]
Sure, I'm open to a pull request implementing the configuration option. I'm currently a bit too busy to do this myself, but it should be trivial.

**Comment by 14mRh4X0r** [comment]
Option to skip verification added with 9326aa4
